name: github

on: 
  push:
    branches:
    -  main

jobs:
  heytharundev:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v4  # grabs your repo code
      - name: install the node
        uses: actions/setup-node@v4
        with:
          node-version : 18



      - name: install react Packages
        run: npm install
      - name: build the react
        run: npm run build

      - name: task2
        run: echo "installed done in ui side"  
# server side it will run these 
  backedn-dev:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v4  # grabs your repo code
      - name: install the node
        uses: actions/setup-node@v4
        with:
          node-version : 18



      - name: install react Packages
        run: npm install

      - name: Backend ready
        run: echo "Backend dependencies installed successfully"

    

