name: MERN Project CI

on:
  push:
    branches:
      - main   # runs only on main branch

jobs:
  frontend:
    name: Frontend Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: cache-NodeModules(Ui)
        uses: actions/cache@v3
        with :
          path : UI/node_modules
          key :  forntend_dev -${{hashFiles('UI/package-lock.json')}}



      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm install
        working-directory: UI

      - name: Build frontend
        run: npm run build
        working-directory: UI

      - name: Frontend done
        run: echo "Frontend build completed"

  backend:
    needs : frontend
    name: Backend Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: cache-nodeModules(backend)
        uses: actions/cache@v3
        with :
          path: backend/node_modules
          key : backed-dev -${{hashFiles('backend/package-lock.json')}}

      - name: Install backend dependencies
        run: npm install
        working-directory: backend

      - name: Backend ready
        run: echo "Backend dependencies installed successfully"
    
  deploy :
      needs : backend
      name : deployment
      runs-on: ubuntu-latest
      steps :
      - name : Deployment
        run : echo "Deployment started"

