name: github

on: push

jobs:
  heytharundev:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout code
         uses: actions/checkout@v4  # grabs your repo code

      - name: simple step
        run: echo "Hello!"
      - name: task2
        run: echo "task2"  
